/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package csvtomt940;

public class App {

    public static void main(String[] args) {
        // Parse closingbalance
        double closingBalance = Double.parseDouble(args[0]);

        CsvToMT940.execute(closingBalance);
    }
}
